one more trigger

diff --git a/python-api-yt/Jenkinsfile b/python-api-yt/Jenkinsfile
--- a/python-api-yt/Jenkinsfile
+++ b/python-api-yt/Jenkinsfile
@@ -1,61 +1,70 @@
-pipeline {
-    agent any
-
-    stages {
-        stage("Setup User/Group IDs") {
-            steps {
-                script {
-                    env.USER_ID = sh(script: 'id -u', returnStdout: true).trim()
-                    env.GROUP_ID = sh(script: 'id -g', returnStdout: true).trim()
-                }
-            }
+pipeline{
+    agent{
+        docker {
+            image  'python:3.11-slim'
+           
         }
-        stage("Checkout Code") {
-            steps {
+    }
+    stages{
+        stage("checkout-code"){
+            steps{
                 checkout scm
+            
             }
         }
-        stage("Check PR Title") {
-            when {
+        stage("PR-name"){
+            when{
                 changeRequest()
             }
-            steps {
-                script {
-                    def title = env.CHANGE_TITLE ?: ""
-                    if (!title.startsWith("PROJ-")) {
-                        error("PR title must start with a JIRA ID like PROJ-1234")
+            steps{
+                script{
+                    def title=env.CHANGE_TITLE ?: ""
+                    if (!title.startsWith("PROJ-")){
+                        error("pr must start with jira id like PROJ-1234")
                     }
                 }
             }
         }
-        stage("Build and Test") {
-            agent {
-                docker {
-                    image 'python:3.11-slim'
-                    args "--user=${env.USER_ID}:${env.GROUP_ID}"
-                }
+        stage("install dependencies"){
+            steps{
+                sh ''' 
+                
+                cat /etc/os-release
+                ls -lart
+                cd python-api-yt
+                ls -lart
+                pip install -r requirements.txt
+            
+                '''
             }
-            steps {
-                sh 'python -m pip install --upgrade pip' // Good practice to update pip first
-                sh 'cd python-api-yt && pip install -r requirements.txt'
-                sh 'cd python-api-yt && python -m pytest -v -s --junitxml=results.xml || true'
+        }
+        stage("run the test"){
+            steps{
+                sh '''
+                cd python-api-yt
+                ls -lart
+                python -m pytest -v -s --junitxml=results.xml || true
+                '''
+            }
+        }
+        stage("archive results"){
+            steps{
+               junit 'python-api-yt/results.xml'
             }
         }
     }
-    
-    post {
-        always {
-            echo 'Archiving test results'
-            junit 'python-api-yt/results.xml'
-            
-            echo 'Cleaning working directory'
+    post{
+        success{
+            echo "Build and test passed"
+        }
+        failure{
+            echo "Build test failed"
+        }
+        always{
+            echo 'Cleaning working dir'
+            sh 'sudo chown -R jenkins:jenkins . || true'
             deleteDir()
         }
-        success {
-            echo "Build and test passed successfully!"
-        }
-        failure {
-            echo "Build and test failed."
-        }
     }
+
 }
